#!/usr/bin/env python3
"""
Deployment script - generated by Telamon
Project: latu-club
"""
import argparse
import subprocess
import sys


FLY_APP = "latu-club"
FLY_REGION = "ams"



def run(cmd, check=True):
    print(f"$ {cmd}")
    return subprocess.run(cmd, shell=True, check=check)


def deploy(prod=False):
    env = "production" if prod else "staging"
    app = FLY_APP if prod else f"{FLY_APP}-staging"

    print(f"Deploying latu-club to {env} ({app})...")

    run(f"fly deploy --app {app} --region {FLY_REGION}")


def main():
    parser = argparse.ArgumentParser(description="Deploy latu-club")
    parser.add_argument("command", choices=["deploy"], help="Command")
    parser.add_argument("--prod", action="store_true", help="Deploy to production")

    args = parser.parse_args()

    if args.command == "deploy":
        deploy(prod=args.prod)


if __name__ == "__main__":
    main()